### PR TITLE
added tax rates save and delete functions

### PR DESCRIPTION
**Pull request by jordanwalsh23**
The get method was already merged.  This PR adds the save and delete methods.

### CODE REVIEW

**Comment by davidbanham** [comment]
The changes here look good, but a lot of the tests have been skipped out. Was that intentional?

**Comment by jordanwalsh23** [comment]
Was just to speed up the tests.. forgot to put them back in. Will update and merge.

**Comment by jordanwalsh23** [comment]
Added the tests back in and ran them.  All good from my end.

**Comment by davidbanham** [comment]
:+1:

**Pull request merged**
