### PR TITLE
Reflect deprecation of entrust certs

### PR DESCRIPTION
**Pull request by davidbanham**
https://developer.xero.com/documentation/auth-and-limits/entrust-certificate-deprecation

I haven't actually been able to test this yet as the code relies on a private key file being present on the filesystem. It would be good to get some documentation on what the contents of this file need to be in order to run the suite.

Better yet might be to pass the key in as a string rather than relying on it being on disk. That way the test suite could pass in whatever testing values it needs.

For production usage, we could either include an `fs.readFileSync` call in the example usage or to maintain backwards compatibility, look for the file if (!passed_in_key).

### CODE REVIEW

**Comment by jordanwalsh23** [comment]
The documentation for the public/private key files is all available on the Xero Developer Portal (developer.xero.com).

This is where you should sign up for your keys to insert into the config files for testing.

The only value you might need to change in your config file for testing Public/Partner apps is the appId on line `158` of `accountingtests.js`.  This is the value behind the select box on the 'Allow Access to your App' screen. I haven't been able to target this field programmatically, so I'm simply referencing it from the test.

Please make sure you run the test suite prior to submitting PRs to ensure all code is working.

**Comment by davidbanham** [comment]
Oh yeah I'm familiar with the procedure for getting actual keys. I wasn't sure what values it needed in order to run the test suite and hadn't yet had a chance to do a review of the tests in order to figure it out from the code.

**Comment by davidbanham** [comment]
Ahh, I see. It's an integration suite hitting the actual endpoints so needs an actual key. No worries.

**Comment by jordanwalsh23** [comment]
Yep, integration tests.

Definitely only run it against a demo company! Will likely be some
undesirable items created if you run against a live org.

**Comment by davidbanham** [comment]
So am I safe to run it with a live Partner org so long as I give the credentials of a demo company in config.XeroUsername and config.XeroPassword ?

**Comment by jordanwalsh23** [comment]
The XeroUsername and XeroPassword fields are only used in the Public/Partner integration tests to automate the OAuth flow.  You don't need these fields with the private app tests.

Most of the tests will create data, then retrieve it to check the marshall/unmarshall of XML works correctly.  *So be warned running it anywhere.*

If you are wanting to extend the SDK, I'd suggest creating a free demo company and running it as a private app integration against that.  This way there's no chance of data corruption.

If you're wanting to build a brand new node.js application to do something specifically in your partner's org, I'd suggest you clone the repo locally, then create a separate application that references this library as a dependency.

e.g. you could have your directory structure like:

```
/xero-node
/my-nodejs-app
```

And in the package.json of your `my-nodejs-app` you could reference the `xero-node` code like:

```
package.json

{
    "name": "my-nodejs-app",
    "version": "1.0.0",
    "description": "Simple script do cool stuff",
    "main": "index.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "preinstall": "npm install ../xero-node"
    },
    "dependencies": {
        "xero-node": "file:../xero-node"
    },
    "repository": {},
    "author": "",
    "license": "MIT"
}
```

Hopefully that makes sense.

This is only the case until i can get this merged with the official Xero repo and push the code up to npm.

**Comment by davidbanham** [comment]
Yep, all makes sense. This PR is about changing the way Partner app API calls are made, so in order to ensure it's correct I'll need to run the Partner section of the test suite. A Private app wouldn't exercise anything to do with the Entrust cert signing.

Incidentally, I usually prefer to call in unpublished modules via git URI rather than referencing a filesystem location. It plays nicer with Docker containers and CI runners and makes the build more repeatable for other developers. ie:

```
"dependencies": {
  "xero-node": "jordanwalsh23/xero-node"
},
```

I'll drop you an email with some more specifics about what we're doing with the library shortly.

**Comment by jordanwalsh23** [comment]
Got it. Yes, then you should use the XeroUsername and XeroPassword fields to automate the OAuth flow.  You will need to do it manually, and when you get to the Org Selection screen (if you have more than one) just use a Chrome Inspect and get the value of the select field.

You can get a URL for this auth process easily enough by introducing a `console.log(authoriseUrl)` on line `102` of `accountingtests.js`.

Once you've got the appid, replace that in line `158`, and zombie will automatically Auth the app for you.

I'd then just suggest using lots of `.skip` functions in the tests, and only exercise the retrieval tests to make sure you're happy with how it's all working.

Agreed, the Github approach is better if you're not making any local changes.

**Comment by davidbanham** [comment]
Okay, got the suite running and successfully made a call without the Entrust certs. It works.

**Pull request merged**
