### PR TITLE
added anonymous usage tracking support using GA. This can be disabled…

### PR DESCRIPTION
**Pull request by jordanwalsh23**
This PR integrates google analytics support to send method usage statistics back to GA using the Measurement Protocol.

The purpose is to give some insights into the methods that are being utilised by the library.

This needs further improvement to also track exceptions as they occur.  Currently this is only tracking positive method calls.

### CODE REVIEW

**Comment by davidbanham** [comment]
As a user of the library this would freak me right out. Anything that deals in my sensitive financial data and sends analytics off site to a third party is a big red flag.

I get that all that's _actually_ being tracked is the amount of times a method was invoked, but that's not obvious to someone casually perusing the code when evaluating whether or not they should use it.

**Comment by jordanwalsh23** [comment]
So you think altered method naming could assist here? Or just drop the
functionality altogether?

The SDKs we have to date have very little analytics as the User-Agent is
being used by the Apps themselves, rather than the SDKs.

I can reduce the requirement, but essentially I want to understand some
usage patterns to help improve the SDK over time.

**Comment by davidbanham** [comment]
I totally get why you're keen to have the analytics from the perspective of the module author. From the perspective of the module user, though, this would give me the wild heebie jeebies.

My advice would be to drop the functionality altogether, since I think it'd turn a lot of people away from the library. Maybe not everyone is as tinfoil hat as me, though.

**Comment by jordanwalsh23** [comment]
After some deliberation, I've decided to close off this PR.  The value gained by the analytics will be quickly diminished by the lost trust of users.

Closing.

**Pull request closed without merging**
